name: AI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize


jobs:

  review:

    runs-on: ubuntu-latest


    steps:

      # Step 1: Download the repository code
      - name: Checkout code
        uses: actions/checkout@v4


      # Step 2: Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # Step 3: Run our AI reviewer script
      - name: Run AI Reviewer
        run: |
          python backend/reviewer.py